//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Added to bring Required and Display into scope.
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AzureDoctor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public Subscription()
        {
            this.CloudServices = new HashSet<CloudService>();
        }
    
        public int SubscriptionRecordID { get; set; }
        [Required(ErrorMessage = "Subscription name is required")]
        [Display(Name = "Subscription name")]
        public string SubscriptionName { get; set; }
        [Required(ErrorMessage = "Azure Subscription ID is required")]
        [Display(Name = "Azure Subscription ID")]
        [StringLength(36, ErrorMessage = "The Azure Subscription ID must be 36 characters long, including hyphens.", MinimumLength = 36)]
        public string AzureSubscriptionID { get; set; }
        public int UserId { get; set; }
        [Required(ErrorMessage = "Phone number is required")]
        [Display(Name = "Phone number in format:3538XXXXXXXX")]
        public string PhoneNumber { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<CloudService> CloudServices { get; set; }
    }
}
