//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureDoctor.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class azuredoctorEntities : DbContext
    {
        public azuredoctorEntities()
            : base("name=azuredoctorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Certificate> Certificates { get; set; }
        public DbSet<CloudService> CloudServices { get; set; }
        public DbSet<InstanceStatu> InstanceStatus { get; set; }
        public DbSet<RequestResult> RequestResults { get; set; }
        public DbSet<Subscription> Subscriptions { get; set; }
    }
}
