//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureDoctor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestResult
    {
        public RequestResult()
        {
            this.InstanceStatus = new HashSet<InstanceStatu>();
        }
    
        public int RequestID { get; set; }
        public int CloudServiceID { get; set; }
        public Nullable<bool> AllInstancesHealthy { get; set; }
        public string DeploymentSlot { get; set; }
        public string InstanceSize { get; set; }
        public string InstanceCount { get; set; }
        public string VIPAddress { get; set; }
        public string Location { get; set; }
        public string HostedServiceStatus { get; set; }
        public string DeploymentStatus { get; set; }
        public string VMStatus { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    
        public virtual CloudService CloudService { get; set; }
        public virtual ICollection<InstanceStatu> InstanceStatus { get; set; }
    }
}
