//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkerRole1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificate
    {
        public int CertRecordID { get; set; }
        public string CertificateName { get; set; }
        public string Thumbprint { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    }
}
