//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkerRole1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public Subscription()
        {
            this.CloudServices = new HashSet<CloudService>();
        }
    
        public int SubscriptionRecordID { get; set; }
        public string SubscriptionName { get; set; }
        public string AzureSubscriptionID { get; set; }
        public int UserId { get; set; }
        public string PhoneNumber { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<CloudService> CloudServices { get; set; }
    }
}
